### A Note on Contributions

Whenever we have team projects, there are always concerns on unequal contributions from members of a project team. In the ideal world, we are all here to put in our best efforts and learn together. Even in that ideal world, we have different skill sets and preparations, and we will still contribute differently to a project. 

Therefore, you are required to post a *contribution statement* in the root README.md of your GitHub repo. Please beware that your GitHub repo will become public and remain public after the due date of the projects. 

Post your title, team members, project abstract and a contribution statement in the README.md file.  This is a common practice for research scientific journals. 

Below is an example. If no contribution statement is provided, we will insert a default statement that goes "**All team members contributed equally in all stages of this project. All team members approve our work presented in this GitHub repository including this contributions statement**. "

---
Sample project README statement.

Project 2 Predictive Modeling: Group 7

Team members: Mao Guan, Michael Sheng, Nicole Smith, Kenny Warner, Jessica Zhang

Summary: In this project, we developed a new method using XGBoost and improved the classification accuracy for images of cats and dogs to 74%. 

[Contribution Statement] As a team, we extracted SIFT features from the .RData files. Mao implemented simple models (RandomForest, SVM, logistic regression, and MLP) using Python. Mao also extracted HOG features. Nicole and Kenny developed the XGBoost model. Michael and Jessica built the CNN. Michael, Nicole, and Kenny developed the baseline classification model for evaluation. Jessica and Nicole prepared the presentation, and Michael, Mao and Kenny organized the Github and main.Rmd file. All team members approve our work presented in our GitHub repository including this contribution statement.
