---
title: "HOG_features"
author: "MaoGuan"
date: "2018年3月1日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load libraries
if(!require(EBImage)){
  source("http://bioconductor.org/biocLite.R")
  biocLite("EBImage")
}
if(!require(OpenImageR)){
  install.packages("OpenImageR")
}

```

```{r }
library(OpenImageR)
library(EBImage)

library(dplyr)
library(pbapply)

img_dir <- "../data/train/"
dir_names <- list.files(img_dir)
num_files <- length(list.files(img_dir))

files <- mixedsort(sort(dir_names))



resized <- pbapply(imgs, function(img) {
  resize(img, 128, 128)})

# test image 1
img0 <- readImage(paste0(img_dir,  files[1])) # change dir_names to files so images are in order pet1, pet2 instead of pet1, pet10. 

h1 <- HOG(img0, cells = 3, orientations = 6)

# store the HOG features
H <- matrix(NA, num_files,length(h1)) 

for(i in 1:num_files){
  img <- readImage(paste0(img_dir, files[i]))
  H[i,] <- HOG(img,cells = 3, orientations = 6)
}

# output features
write.csv(H, file = "../output/hog_features.csv",row.names = F)
```

